# Tooth Caries Detection with Detectron2 Configuration

project:
  name: "tooth_caries_detection"
  description: "Tooth caries detection using Faster R-CNN with Detectron2."
  version: "1.0.0"
  task_type: "object_detection"

# 数据配置
data:
  # 数据路径
  root_dir: "data"
  raw_dir: "data/raw"
  images_dir: "data/raw/images"
  labelme_dir: "data/raw/labelme"
  processed_dir: "data/processed"
  annotations_dir: "data/annotations"
  splits_dir: "data/splits"
  
  # 数据格式
  input_format: "labelme"
  output_format: "coco"
  image_extensions: [".jpg", ".jpeg", ".png", ".bmp"]
  annotation_extension: ".json"
  
  # 图像处理
  image_config:
    min_size: 800
    max_size: 1333
    keep_aspect_ratio: true
  
  # 数据分割
  split_ratios:
    train: 0.7
    val: 0.2
    test: 0.1
  random_seed: 42
  
  # 类别配置
  classes:
    "toothCaries": 1
  num_classes: 1
  
  # 数据加载
  dataloader:
    batch_size: 2
    num_workers: 4
    shuffle: true

# Detectron2模型配置
model:
  config_file: "COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml"
  weights: "COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml"
  device: "cuda"
  
  # 模型参数
  roi_heads:
    score_thresh_test: 0.5
    nms_thresh_test: 0.5
    num_classes: 1

# 训练配置
training:
  max_iter: 3000
  base_lr: 0.00025
  lr_scheduler_name: "WarmupMultiStepLR"
  warmup_iters: 1000
  steps: [2000, 2500]
  gamma: 0.1
  
  # 训练监控
  checkpoint_period: 500
  eval_period: 500
  log_period: 100
  
  # 输出目录
  output_dir: "experiments/detectron2_output"

# 验证配置
validation:
  metrics: ["bbox"]

# 推理配置
inference:
  model_path: "experiments/detectron2_output/model_final.pth"
  score_threshold: 0.5
  output_dir: "experiments/predictions"
  save_visualizations: true

# 路径配置
paths:
  train_json: "data/annotations/train_coco.json"
  val_json: "data/annotations/val_coco.json"
  test_json: "data/annotations/test_coco.json"

# 日志配置
logging:
  level: "INFO"
  log_dir: "experiments/logs"

# 硬件配置
hardware:
  device: "cuda"
  mixed_precision: true
